### PR TITLE
Bug imei settings

### LINKED ISSUE #1579: On settings, show IMEI
Hidden under show developers options

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Close #1579

### CODE REVIEW

File: app/src/main/java/org/eyeseetea/malariacare/domain/usecase/GetDeviceUseCase.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
+package org.eyeseetea.malariacare.domain.usecase;
+
+import org.eyeseetea.malariacare.domain.boundary.executors.IMainExecutor;
+import org.eyeseetea.malariacare.domain.boundary.repositories.IDeviceRepository;
+import org.eyeseetea.malariacare.domain.entity.Device;
+
+public class GetDeviceUseCase implements UseCase {
```
Comment (xurxodev) [inline app/src/main/java/org/eyeseetea/malariacare/domain/usecase/GetDeviceUseCase.java:8]: use cases should use AsyncExecutor to retrieve data from data layer and MainExecutor to notify presentation layer

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio I have requested some changes, can you review it please?

File: app/src/main/java/org/eyeseetea/malariacare/domain/usecase/GetDeviceUseCase.java (hunk 1 above)
Comment (manuelplazaspalacio) [reply app/src/main/java/org/eyeseetea/malariacare/domain/usecase/GetDeviceUseCase.java:8]: But the device info is not in data layer, it's an Android service.

Comment (xurxodev) [reply app/src/main/java/org/eyeseetea/malariacare/domain/usecase/GetDeviceUseCase.java:8]: well, we can do two things:
- use AsyncExecutor and MainExecutor as in other use cases for we have a standard way, this is better option for me.
- Does not use AsyncExecutor and MainExecutor because really here does not communicate with a database or remote service. 

But you are using only main executor in your solution and this option has no sense

**Comment by manuelplazaspalacio** [comment]
Changes done @xurxodev

**Review by xurxodev — APPROVED** [review]
thanks @manuelplazaspalacio
