### PR TITLE
Feature fix lao cambodia bugs

### LINKED ISSUE #779: Laos & Cambodia bugs
- [x] PopulateDB exception
- [x] Add scroll on confirmation screens
- [x] Bug on populate
- [x] Positive int Single question validation error

- [x]  Phone single question  fields validation error
- [x] Multiclick is not controlled
- [x] Swipe not working on read only mode
- [x] Warnings and remminders custom font size doesn't work

### PR DESCRIPTION
**Pull request by idelcano**
Closes #779

### CODE REVIEW

File: app/src/main/java/org/eyeseetea/malariacare/domain/entity/Credentials.java [hunk 1]
```diff
@@ -56,4 +58,12 @@ public int hashCode() {
                 password.hashCode();
     }
 
+    public boolean isLogged() {
```
Comment (idelcano) [inline app/src/main/java/org/eyeseetea/malariacare/domain/entity/Credentials.java]: You can ignore it at this moment, this is solved in the next PR ( https://github.com/EyeSeeTea/pictureapp/pull/980 ) This is only a temporal solution.

File: app/src/main/java/org/eyeseetea/malariacare/views/question/singlequestion/PhoneSingleQuestionView.java [hunk 2]
```diff
@@ -79,13 +80,20 @@ public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
...
 
     private void validateAnswer(Context context) {
-        try {
-            Phone phone = new Phone(mCustomEditText.getText().toString());
-            hideKeyboard(mCustomEditText);
-            notifyAnswerChanged(phone.getValue());
-            Validation.getInstance().removeInputError(mCustomEditText);
-        } catch (InvalidPhoneException e) {
-            Validation.getInstance().addinvalidInput(mCustomEditText, context.getString(R.string.dynamic_error_phone_format));
+        if (!isClicked) {
```
Comment (idelcano) [inline app/src/main/java/org/eyeseetea/malariacare/views/question/singlequestion/PhoneSingleQuestionView.java]: Sorry @xurxodev  but i don't know how do it. Do you have any idea?

**Comment by idelcano** [comment]
@xurxodev You can review it again.
Finally, I did a refactor of the keyboard control click.
