### PR TITLE
fix dialog screen resize

### LINKED ISSUE #385: Warning and error dialog do not display properly in some devices
screenshot from 2016-08-13 17 54 31
screenshot from 2016-08-13 18 41 17

### PR DESCRIPTION
**Pull request by idelcano**
Closes #385

### CODE REVIEW

File: app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java [hunk 1]
```diff
@@ -493,28 +493,22 @@ public View getView(int position, View convertView, ViewGroup parent) {
                 break;
             case Constants.REMINDER:
             case Constants.WARNING:
-                TableRow.LayoutParams params = new TableRow.LayoutParams(TableRow.LayoutParams.MATCH_PARENT, TableRow.LayoutParams.MATCH_PARENT,0.5f);
 
-                int paddingSize= (int) PreferencesState.getInstance().getContext().getResources().getDimension(R.dimen.question_padding);
-
-                tableRow=(TableRow)lInflater.inflate(R.layout.dynamic_tab_row_singleitem, tableLayout, false);
-                tableRow.setLayoutParams(params);
+                tableRow=(TableRow)lInflater.inflate(R.layout.dynamic_tab_row_question_text, tableLayout, false);
```
Comment (adrianq) [inline app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/DynamicTabAdapter.java]: @idelcano I am going to merge it (it works as a charm!) but we are initialising tableRow twice here. This code can be refactor a little bit but obviously this is not the right moment!

**Comment by adrianq** [comment]
@idelcano Thanks! It works! :)
