### PR TITLE
Fix bug, get survey from query not from session on reloadAnswered

### LINKED ISSUE #380: reloadAnswered survey from Session crash on restart.
Is necessary get the survey from db not from session.

### PR DESCRIPTION
**Pull request by idelcano**
Closes #380

### CODE REVIEW

File: app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java [hunk 1]
```diff
@@ -865,6 +866,18 @@ public void removeChildrenValuesFromQuestionRecursively(Question question) {
             }
         }
     }
+    /**
```
Comment (adrianq) [inline app/src/main/java/org/eyeseetea/malariacare/database/model/Survey.java]: @idelcano can you move this method to Survey.java?
