### PR TITLE
Bug not showing ifoche surveys in unsent

### LINKED ISSUE #1222: when I create a new survey with ifoche user this survey not appear in open list

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Close #1222

### CODE REVIEW

File: app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java [hunk 1]
```diff
@@ -146,21 +152,35 @@ protected void onHandleIntent(Intent intent) {
 
     private void reloadDashboard() {
         Log.i(TAG, "reloadDashboard");
-        List<Survey> surveys = Survey.getAllSurveys();
+        IProgramRepository programLocalDataSource = new ProgramLocalDataSource();
+        IMainExecutor mainExecutor = new UIThreadExecutor();
+        IAsyncExecutor asyncExecutor = new AsyncExecutor();
+        GetUserProgramUIDUseCase getUserProgramUIDUseCase = new GetUserProgramUIDUseCase(
```
Comment (xurxodev) [inline app/src/main/java/org/eyeseetea/malariacare/services/SurveyService.java]: Execution of this use case realize a query to database in every reload method, can you refactor for execute one time in service entry point (constructor onCreate)

**Comment by manuelplazaspalacio** [comment]
@xurxodev Changes done
