### PR TITLE
Solved bug not allowing to reach review screen

### LINKED ISSUE #1581: scrolling forward doesn't allow you to reach the review screen (blocks in last question)

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Close #1581

### CODE REVIEW

File: app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/NavigationController.java [hunk 1]
```diff
@@ -111,6 +111,9 @@ public boolean isNextAllowed() {
         OptionDB currentOptionDB = currentValueDB == null ? null : currentValueDB.getOptionDB();
         //Find next node with current option
         boolean isAllowed = findNext(currentOptionDB) != null;
+        if (!isAllowed && !hasNext(null) && !hasNext(currentValueDB.getOptionDB())) {
```
Comment (xurxodev) [inline app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/NavigationController.java]: @manuelplazaspalacio I think that we should not change this method of NavigationController for this because we are modifying a existed method that using several apps and several scenarios and is possible that we are changing a behavior. I think we should change caller (onSwipeLeft) for this method and create new condition to know if is the last question

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio  I have requested you some changes, can you review it?

File: app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/NavigationController.java (hunk 1 above)
Comment (manuelplazaspalacio) [reply app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/navigation/NavigationController.java]: This method is only called from onSwipeLeft method of dyanmicTabAdapter. And I think if its the las question that it's the correct behaviour for all apps.

**Comment by manuelplazaspalacio** [comment]
Changes done @xurxodev

**Review by xurxodev — APPROVED** [review]
thanks @manuelplazaspalacio
